simplifies the archiving

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -77,20 +77,21 @@ jobs:
           echo "Extracted version: $VERSION"
           echo "version=$VERSION" >> $GITHUB_ENV
 
-      - name: Zip documentation folder
-        run: |
-          DOCS_DIR="packages/headless/docs"
-          if [ ! -d "$DOCS_DIR" ]; then
-            echo "Documentation folder $DOCS_DIR not found."
-            exit 1
-          fi
+      # - name: Zip documentation folder
+      #   run: |
+      #     DOCS_DIR="packages/headless/docs"
+      #     if [ ! -d "$DOCS_DIR" ]; then
+      #       echo "Documentation folder $DOCS_DIR not found."
+      #       exit 1
+      #     fi
 
-          ZIP_NAME="headless-docs-${{ env.version }}.zip"
-          zip -r "$ZIP_NAME" "$DOCS_DIR"
-          echo "Created zip file: $ZIP_NAME"
+      #     ZIP_NAME="headless-docs-${{ env.version }}.zip"
+      #     zip -r "$ZIP_NAME" "$DOCS_DIR"
+      #     echo "Created zip file: $ZIP_NAME"
 
       - name: Upload documentation artifact
         uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4
         with:
           name: headless-docs-${{ env.version }}
-          path: headless-docs-${{ env.version }}.zip
+          path: packages/headless/docs
+`
